
language: java

jdk:
 - openjdk8
 - openjdk11
 
  addons:
    sonarcloud: 
      organization: andreadepaolis95
        token: 
          secure: K7_hiLYPZYWrVa9rCQqNtA

 
script:
  - ant build
  - sonar-scanner


  
